### ISSUE TITLE
using 'installr' to update to latest R version

### ISSUE THREAD

**Issue by RadioPete24** [talgalili/installr#68]
Attempting to use installr to move from R version 3.3.0 to R 3.3.1, however, a warning message returns:
Warning message:
package 'installr' is not available (for R version 3.3.0).

tried running from R with
install.packages('installr', repos = 'http://cran.us.r-project.org')

**Comment by talgalili** [comment]
What is your sessionInfo() ?

**Comment by yarenty** [comment]
Have the same between 3.3.1 and update to 3.3.2  - typical catch 22 ;-)
install.packages('installr', repos = 'http://cran.us.r-project.org')
Warning message:
package ‘installr’ is not available (for R version 3.3.1)

**Comment by talgalili** [comment]
@yarenty are you using Windows?

**Comment by yarenty** [comment]
Hi @talgalili  I'm on Mac.
I sorted it by getting full new R package...

**Comment by martzkb** [comment]
Hi @yarenty. Could you explain this solution in more detail? I am very new to R and seeing the same issue trying to update from 3.2.1.

**Comment by yarenty** [comment]
there are actually 2 issues: update R and update existing packages:
https://yarenty.blogspot.ie/2016/11/r-upgrade-all-packages.html

I solved that in 2 ways, as you can see, but will suggest first go with easy way - and tell me if it works,  easy way is:

update.packages()
update.packages(ask = FALSE, dependencies = c('Suggests'))

**Comment by mvnarvaezt** [comment]
I keep getting   package 'installr' is not available (for R version 3.4.1)
I tried your suggestion, but it is still not working....

Help...

**Comment by talgalili** [comment]
@mvnarvaezt - what is your operating system?

**Comment by mvnarvaezt** [comment]
Oh I forgot to mention it. 
It is macOs Sierra (10.12.6)

**Comment by talgalili** [comment]
installr is only for Windows OS.

**Comment by RadioPete24** [comment]
Will it be available for a macOS?

**Comment by RadioPete24** [comment]
I used to run it on my mac

**Comment by talgalili** [comment]
That is not likely.

**Comment by yarenty** [comment]
Hi all!!
I just suddenly got notification from past year, about article that I put
there some time ago.
First - sorry I didn't know that there are guys who.. reading my articles,
 not to mention - looking for some more details ..
Answer: Yes, I'm on Mac, but I usually double check on ubuntu.

I see that  this issue is closed now.

My new task: find why I didn't get info earlier, and fix it ...
Jaro

**Comment by EhoumanEvans** [comment]
I am using  R version 3.6.1 (2019-07-05) with RStudio version ‘1.2.5001’. I wish to update to R version 4 using the  _installr_ package on macOS HighSierra 10.13.6. However, when I try to install it I have the following message : Warning in install.packages :
  package ‘installr’ is not available (for R version 3.6.1).  

It seems that since 2017 there have been no solution for Mac users?

**Comment by talgalili** [comment]
installr is only for Windows.
