### ISSUE TITLE
install.miktex fails due to url change

### ISSUE THREAD

**Issue by vnijs** [talgalili/installr#71]
It seems that the download url for miktex has changed. See below for current link.

http://miktex.org/download/ctan/systems/win32/miktex/setup/basic-miktex-2.9.6069-x64.exe

**Comment by talgalili** [comment]
The new URL seems to redirect here:
http://latex.imamu.edu.sa/tex-archive/systems/win32/miktex/setup/basic-miktex-2.9.6069-x64.exe
And this link does not seem to work. Are you able to download the file manually?

**Comment by vnijs** [comment]
The links seem to work now.

**Comment by talgalili** [comment]
I've pushed a new version of installr, for which `install.MikTeX` now seems to work. 

Thanks for the report.

**Comment by vnijs** [comment]
Having trouble with install.miktex() again. It looks like it is just downloading miktex.org and completed in a few seconds which is unlikely given the size of miktex. See full output below.

> installr::install.miktex()
============= Which version of MiKTeX do you want? ====================
  version
1      32
2      64
Please review the table of versions from above,
and enter the row number of the file-version you'd like to install: 2
trying URL 'http://miktex.org'
Content type 'text/html; charset=utf-8' length unknown
downloaded 13 KB

The file was downloaded successfully into:
 C:\Users\vnijs\AppData\Local\Temp\RtmpMrj2g3/miktex.org 

Running the installer now...

Installation status:  TRUE . Removing the file:
 C:\Users\vnijs\AppData\Local\Temp\RtmpMrj2g3/miktex.org 
 (In the future, you may keep the file by setting keep_install_file=TRUE)

**Comment by talgalili** [comment]
Thanks @vnijs 
Solved it, and pushed the fix to github.

Cheers,
Tal

**Comment by ShrewMaster** [comment]
This is not working again in version 0.21.0. I got the following error:

`install.MikTeX()`

Explanation of the error: You didn't enter a valid .EXE URL. 
This is likely to have happened because there was a change in the URL of the installer file in the download page of the software (making our function unable to know what to download). 

This might have already been fixed in the latest version of installr. Install the latest version of installr using devtools::install_github('talgalili/installr') and try again.

If this doesn't help please e-mail: tal.galili@gmail.com and let me know this function needs updating/fixing (please include the output of sessionInfo() ) - thanks!

We failed to download the file into:
 C:\Users\FOliveira\AppData\Local\Temp\RtmpwFfXCJ/NA 
(i.e.: the installation failed)

**Comment by talgalili** [comment]
Thanks, this is now fixed in the most recent version on github.
